### ISSUE TITLE
Manage state with Compose TextField value lagging

### ISSUE THREAD

**Issue by IbrahimDisouki** [orbit-mvi/orbit-mvi#124] opened 2022-04-05 20:38 UTC
I really would like to thank you all for the amazing library that makes our life easier.
I'm trying to manage Compose state following the [state-hoisting](https://developer.android.com/jetpack/compose/state#state-hoisting) concept as recommended by Google.
The problem is that makes TextField writing or clearing lagging. check my code:
```
@Composable
fun LoginScreen(viewModel: LoginViewModel = hiltViewModel()) {
    val localFocusManager = LocalFocusManager.current
    val spacing = LocalSpacing.current
    val state = viewModel.collectAsState().value
    Column(
        modifier = Modifier.fillMaxSize(),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Username(
            localFocusManager = localFocusManager,
            username = state.username,
            onUsernameChange = { viewModel.onUsernameChanged(it) })
        Spacer(modifier = Modifier.height(spacing.spaceMedium))
        OutlinedTextField(
            value = state.password,
            onValueChange = { viewModel.onPasswordChanged(password = it) },
            label = { Text(stringResource(id = R.string.password)) },
            visualTransformation = PasswordVisualTransformation(),
            keyboardOptions = KeyboardOptions(
                keyboardType = KeyboardType.Password,
                imeAction = ImeAction.Done
            ),
            keyboardActions = KeyboardActions(onDone = { localFocusManager.clearFocus() })
        )
        Spacer(modifier = Modifier.height(spacing.spaceMedium))
        Button(onClick = { viewModel.login() }) {
            Text(text = stringResource(id = R.string.login))
        }
    }
}

@Composable
fun Username(
    localFocusManager: FocusManager,
    username: String,
    onUsernameChange: (String) -> Unit
) {
    OutlinedTextField(
        value = username,
        onValueChange = onUsernameChange,
        label = { Text(stringResource(id = R.string.username)) },
        keyboardOptions = KeyboardOptions(imeAction = ImeAction.Next),
        keyboardActions = KeyboardActions(onNext = { localFocusManager.moveFocus(FocusDirection.Down) })
    )
}
```
ViewModel:
```
@HiltViewModel
class LoginViewModel @Inject constructor(
    savedStateHandle: SavedStateHandle,
    private val loginUseCase: LoginUseCase
) : ViewModel(), ContainerHost<LoginState, LoginSideEffect> {

    override val container by lazy {
        container<LoginState, LoginSideEffect>(
            initialState = LoginState(),
            savedStateHandle = savedStateHandle
        )
    }

    fun onUsernameChanged(username: String) = intent {
        reduce { state.copy(username = username) }
    }

    fun onPasswordChanged(password: String) = intent {
        reduce { state.copy(password = password) }
    }

    fun login() = intent {
        val loginResult = loginUseCase.invoke(LoginParams(state.username, state.password))
        reduce { state.copy(loginResult = loginResult) }
    }

}
```
LoginState:
```
@Parcelize
data class LoginState(
    val username: String = "",
    val password: String = "",
    val loginResult: Result<UserEntity>? = null
) : Parcelable
```
It happens when I write long text and then click and hold on the `X` button on the keyboard it supposes to clear all characters but it stops after clearing a number of characters.
Any suggestion to solve this without using `var username by remember { mutableStateOf("") }`?

**Comment by mattmook** [comment] 2022-06-15 08:04
Issue linked to https://github.com/orbit-mvi/orbit-mvi/issues/82?

**Comment by Rosomack** [comment] 2022-11-10 05:52
Closing as duplicate of #82

**Closed by Rosomack** 2022-11-10 05:52 UTC
